### PR TITLE
Add Join::into_inner()

### LINKED ISSUE #4: Ability to split a `Join` back into 2 original streams
Hi Daniel,

Long time, no see. :)

I was refactoring `zbus::SignalStream` and needed to get back my orignal `MessageStream` back from a `Join` for that. The use case is almost identical to your code [here](https://gitlab.freedesktop.org/dbus/zbus/-/blob/main/zbus/src/proxy.rs#L318), except after the `next` call, I would like to keep the stream around.

### PR DESCRIPTION
**Pull request by zeenix**
Add a method to allows splitting back into the source streams.

Fixes #4.

### CODE REVIEW

**Comment by danieldg** [comment]
As implemented, `Join::into_inner` might drop an item from the stream if one is buffered.  This should at least be mentioned in the documentation if there is no way to get that item out (or even tell it was there).

Otherwise, looks good and I think it's a useful addition.

**Comment by zeenix** [comment]
> As implemented, `Join::into_inner` might drop an item from the stream if one is buffered. This should at least be mentioned in the documentation if there is no way to get that item out (or even tell it was there).

Good point. I'm still trying to wrap my head around the code but is that when `JoinState` is either `A` or `B`?

**Comment by zeenix** [comment]
@danieldg PTALA.

**Comment by danieldg** [comment]
> > As implemented, `Join::into_inner` might drop an item from the stream if one is buffered. This should at least be mentioned in the documentation if there is no way to get that item out (or even tell it was there).
> 
> Good point. I'm still trying to wrap my head around the code but is that when `JoinState` is either `A` or `B`?

Yes; those states represent that one stream has an item ready, but we're not yet sure it should be the next item because the second stream isn't ready.

The new `Join::into_inner` looks better (although more complex); however, I think it may be useful to also return the Ordering item (which is currently being discarded).  While `zbus` can easily reconstruct it from the Item, that may not be true in general.

**Comment by zeenix** [comment]
> The new `Join::into_inner` looks better (although more complex); however, I think it may be useful to also return the Ordering item (which is currently being discarded). While `zbus` can easily reconstruct it from the Item, that may not be true in general.

That's an easy thing to fix (and I actually already fixed it locally) but I'm not sure about its usefulness. Given that you can only have 1 item queued at a time, what would the caller do with the ordering?

Also talking of that, I'm wondering if it can be of any use to know which stream the queued item is from? :thinking: If it's not useful to know that, the return value could be `(A, B, Option<A::Data>)` instead.

**Comment by zeenix** [comment]
> Also talking of that, I'm wondering if it can be of any use to know which stream the queued item is from? thinking If it's not useful to know that, the return value could be `(A, B, Option<A::Data>)` instead.

Thought more about it and I don't think it matters which stream the item is from. Users will typically have to map the item anyway if that distinction is important to them. So I ended up with the solution I just pushed.

---

@danieldg If you don't have the time/motivation to maintain this crate, kindly consider adding me as the maintainer. Not sure if you got my email about this earlier this week but I don't want to fork this, especially given that I don't have a very good grasp over the code (can be fixed though).

**Comment by zeenix** [comment]
> @danieldg If you don't have the time/motivation to maintain this crate, kindly consider adding me as the maintainer. Not sure if you got my email about this earlier this week but I don't want to fork this, especially given that I don't have a very good grasp over the code (can be fixed though).

Ok, I really think you are barely available anymore to do even the minimum maintenance and I really need the new API for the next zbus release. So went ahead and published my fork as `ordered-streams`. I hope you understand.

**Pull request merged**
